// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixpVZhpNpyPxQsxOu8DxH_DPTMvdFiaI',
    appId: '1:120410408525:web:3ae01b432dd08624f33e04',
    messagingSenderId: '120410408525',
    projectId: 'where-in-the-law-bf730',
    authDomain: 'where-in-the-law-bf730.firebaseapp.com',
    storageBucket: 'where-in-the-law-bf730.firebasestorage.app',
    measurementId: 'G-ZM9FMVNW7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg06QJWQ2S8oX0YuPYx3-OmUIASZXBXE4',
    appId: '1:120410408525:android:fb689d67858838f9f33e04',
    messagingSenderId: '120410408525',
    projectId: 'where-in-the-law-bf730',
    storageBucket: 'where-in-the-law-bf730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6LL23LLSvtPSZ7X5IFBwZ_mboQ2megTg',
    appId: '1:120410408525:ios:93a2d9df91f289d4f33e04',
    messagingSenderId: '120410408525',
    projectId: 'where-in-the-law-bf730',
    storageBucket: 'where-in-the-law-bf730.firebasestorage.app',
    iosBundleId: 'com.example.whereInTheLaw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6LL23LLSvtPSZ7X5IFBwZ_mboQ2megTg',
    appId: '1:120410408525:ios:93a2d9df91f289d4f33e04',
    messagingSenderId: '120410408525',
    projectId: 'where-in-the-law-bf730',
    storageBucket: 'where-in-the-law-bf730.firebasestorage.app',
    iosBundleId: 'com.example.whereInTheLaw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDixpVZhpNpyPxQsxOu8DxH_DPTMvdFiaI',
    appId: '1:120410408525:web:c295cfe86be0c4faf33e04',
    messagingSenderId: '120410408525',
    projectId: 'where-in-the-law-bf730',
    authDomain: 'where-in-the-law-bf730.firebaseapp.com',
    storageBucket: 'where-in-the-law-bf730.firebasestorage.app',
    measurementId: 'G-HQ9TMP6YDE',
  );
}
